spring.application.name=audit-brain

spring.datasource.url=jdbc:postgresql://localhost:5432/aegisdb
spring.datasource.username=postgres
spring.datasource.password=chathu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=9090